#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xb5c97a0d, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf3017e21, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0x82856b93, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0xb5ddb023, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x6b1abcee, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x1858caa3, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x9f1ec650, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0x2a07688c, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0x33077361, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0xc1782359, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0x5f6af414, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0x5237da88, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x42b00eba, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x6b5335a7, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xb6efeeb4, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0x9700966d, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x6b5c4fe3, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0xbff0ab48, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0x3de55af6, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x1d67862b, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0x1170f9b, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0x5ca46e99, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xf9c97411, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x1ecbb142, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0x485c6f35, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xbba2e2ab, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0xa3c52474, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xf79280bf, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0x55312da4, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x6b5e8d81, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0x71bc64b4, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x89a4982e, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x97b69043, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xa0658c45, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0xdc8cb9d7, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x678f91b6, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0x37a73873, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0x1ba7c4bf, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0x2deda4a1, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x5540312c, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xe4fdc50, __VMLINUX_SYMBOL_STR(inet_csk_search_req) },
	{ 0x44f0b164, __VMLINUX_SYMBOL_STR(inet_csk_delete_keepalive_timer) },
	{ 0xfe0b182c, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0x88b454fd, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xfd87876c, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0x1ea06663, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x77b3e039, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x5ca18ad9, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0xaa0675de, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0xd86c0353, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0xf4406e45, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0x9a123b7, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x2913ac9d, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xa20ce1b8, __VMLINUX_SYMBOL_STR(net_msg_warn) },
	{ 0xb0ba5fa7, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0x8d5da549, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0x2ebe4bd5, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x73eca7c9, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0xc59b8904, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x5f31360e, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x77a65690, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0x3ff62317, __VMLINUX_SYMBOL_STR(local_bh_disable) },
	{ 0x90e9ff51, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0xe9739ae8, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0xb0e93b81, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x46058283, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0xf6d4ed20, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0xcdd38334, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0x3a1fc9e8, __VMLINUX_SYMBOL_STR(__ip_route_output_key) },
	{ 0xdf82a3b4, __VMLINUX_SYMBOL_STR(sk_release_kernel) },
	{ 0xb60ba5c9, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xcd08b124, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x59710510, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x642cc58c, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0x799aca4, __VMLINUX_SYMBOL_STR(local_bh_enable) },
	{ 0xd7cb77a9, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xe65df1f2, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0xe14a251e, __VMLINUX_SYMBOL_STR(__inet_hash_nolisten) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x2098973, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0xe35eee8d, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0xddde3c32, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x49da4f9b, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x275de30d, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x114433ca, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0xa797a7af, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x7663a323, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xe718f603, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0xb46a09cd, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x47cd208d, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0xf2e295ed, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0x96d73cdb, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x1488da67, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x69f2aa02, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x7db4a8ce, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x8dc1dfb8, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x2fe31438, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0xbfdc990b, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0xa624c2a0, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";

